# 定义API版本为apps/v1
apiVersion: apps/v1
# 定义资源类型为Deployment
kind: Deployment
# 元数据部分
metadata:
  # 部署的名称为vuexy
  name: vuexy
# 规格说明
spec:
  # 定义副本数量为1
  replicas: 1
  # 选择器配置
  selector:
    # 匹配标签
    matchLabels:
      # 选择app=vuexy的Pod
      app: vuexy
  # Pod模板配置
  template:
    # Pod元数据
    metadata:
      # Pod标签
      labels:
        # 设置app=vuexy标签
        app: vuexy
    # Pod规格
    spec:
      # 容器配置
      containers:
        # 容器详细配置
        - name: vuexy # 容器名称
          image: vuexy:latest # 使用的镜像
          imagePullPolicy: IfNotPresent # 镜像拉取策略
          ports:
            - containerPort: 80 # 容器暴露的端口
---
# 定义API版本为v1
apiVersion: v1
# 定义资源类型为Service
kind: Service
# 元数据部分
metadata:
  # 服务名称为vuexy
  name: vuexy
# 规格说明
spec:
  # 服务类型为NodePort
  type: NodePort
  # 选择器配置
  selector:
    # 选择app=vuexy的Pod
    app: vuexy
  # 端口配置
  ports:
    # 端口详细配置
    - port: 80 # 服务端口
      targetPort: 80 # 目标端口(容器端口)
      nodePort: 30080 # 节点端口(外部访问端口)