# Deployment 资源定义，用于声明 vuexy 应用的副本和运行方式
apiVersion: apps/v1  # API 版本，K8s 1.9+ 推荐 apps/v1
kind: Deployment     # 资源类型，这里是 Deployment
metadata:
  name: vuexy        # Deployment 的名称
spec:
  replicas: 1        # 副本数，运行 1 个 Pod
  revisionHistoryLimit: 3 # 保留的旧版本数量
  strategy:
    canary:
      steps:
        - pause: {}  # 在开发，测试环境，不需要暂停， 在生产环境需要暂停
        - setWeight: 100
        # Refer to https://argo-rollouts.readthedocs.io/en/stable/features/canary/
        # Example:
        # - pause: {}
        # - setWeight: 33
      # - pause: { duration: 10s }
  selector:
    matchLabels:
      app: vuexy     # 选择标签，和下面 template 的 labels 匹配
  template:
    metadata:
      labels:
        app: vuexy   # Pod 的标签，和 selector 匹配
    spec:
      containers:
        - name: vuexy                # 容器名称
          image: vuexy:latest        # 使用的镜像名:tag，需提前 build 好
          imagePullPolicy: IfNotPresent # 优先使用本地镜像
          ports:
            - containerPort: 80      # 容器对外暴露的端口 