apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuexy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuexy
  template:
    metadata:
      labels:
        app: vuexy
    spec:
      containers:
        - name: vuexy
          image: vuexy:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80 